# Generated by Django 5.0.3 on 2024-04-13 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.TextField(verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('client', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_part_face', models.CharField(max_length=50, verbose_name='Часть лица')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.posts')),
            ],
        ),
        migrations.CreateModel(
            name='Shades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_shade', models.CharField(max_length=50, verbose_name='Оттенок')),
                ('part_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.partface')),
            ],
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.TextField(verbose_name='Фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPartFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_part_face', models.CharField(max_length=50, verbose_name='Часть лица')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.userimages')),
            ],
        ),
        migrations.CreateModel(
            name='UserShades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_shade', models.CharField(max_length=100, verbose_name='Оттенок')),
                ('user_part_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.userpartface')),
            ],
        ),
    ]
